const $=id=>document.getElementById(id);const euro=n=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(n)||0);const nowISO=()=>new Date().toISOString().slice(0,10);const STORE='dealers-v26-data';
const ACCOUNTS={current:'Conta corrente',savings:'Poupança',yield:'Dinheiro a render',carFund:'Fundo carro',exterior:'Exterior',insurance:'Reserva do seguro'};
const defaults={theme:'dark',balances:{current:0,savings:0,yield:0,carFund:0,exterior:0,insurance:0},savingGoal:7000,carGoal:2000,portfolio:{invested:0,market:0},loan:{balance:0,initial:0,payment:0,day:3,history:[]},transactions:[],pending:[],reserves:[],closures:[]};
let data=load();function load(){try{return merge(defaults,JSON.parse(localStorage.getItem(STORE)||'{}'))}catch{return structuredClone(defaults)}}function merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a;if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=merge(a[k],b?.[k]);for(const k of Object.keys(b||{}))if(!(k in o))o[k]=b[k];return o}return b??a}function save(){localStorage.setItem(STORE,JSON.stringify(data));render()}
const monthKey=d=>String(d).slice(0,7);const thisMonth=()=>nowISO().slice(0,7);const txMonth=t=>monthKey(t.budgetMonth||t.date);const currentMonthTx=()=>data.transactions.filter(t=>txMonth(t)===thisMonth());
function mainWealth(){const b=data.balances;return b.current+b.savings+b.yield+b.carFund+b.exterior}function reserved(){return data.reserves.filter(r=>r.status==='pending'&&r.month===thisMonth()).reduce((s,r)=>s+r.amount,0)}function saved(){return data.balances.savings+data.balances.yield}function monthStats(){const tx=currentMonthTx();const income=tx.filter(t=>t.type==='income'&&t.budget!==false).reduce((s,t)=>s+t.amount,0);const expense=tx.filter(t=>t.type==='expense'&&t.budget!==false).reduce((s,t)=>s+t.amount,0);const res=reserved();return{income,expense,res,available:income-expense-res}}
function accountOptions(select,allowBlank=true){select.innerHTML=(allowBlank?'<option value="">—</option>':'')+Object.entries(ACCOUNTS).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}
function debit(acc,amount){if(acc&&data.balances[acc]!=null)data.balances[acc]-=amount}function credit(acc,amount){if(acc&&data.balances[acc]!=null)data.balances[acc]+=amount}
function render(){document.documentElement.dataset.theme=data.theme;const mw=mainWealth(),res=reserved(),st=monthStats();$('mainWealth').textContent=euro(mw-res);$('wealthWithReservations').textContent=euro(mw);$('stateAvailable').textContent=euro(mw-res);$('stateReserved').textContent=euro(res);$('stateSaved').textContent=euro(saved());$('homeIncome').textContent=euro(st.income);$('homeSpent').textContent=euro(st.expense);$('homeReserved').textContent=euro(st.res);$('homeBudgetAvailable').textContent=euro(st.available);$('homeCurrent').textContent=euro(data.balances.current);$('homeExterior').textContent=euro(data.balances.exterior);$('homeSavings').textContent=euro(data.balances.savings);$('homeYield').textContent=euro(data.balances.yield);$('homeCarFund').textContent=euro(data.balances.carFund);$('homePortfolio').textContent=euro(data.portfolio.market);$('homeExpenses').textContent=euro(st.expense);
const pend=data.pending.filter(p=>p.status==='pending');$('pendingCount').textContent=pend.length;$('pendingTotal').textContent=euro(pend.reduce((s,p)=>s+p.amount,0));$('expensePendingTitle').textContent=euro(pend.reduce((s,p)=>s+p.amount,0));
$('wealthMain').textContent=euro(mw);$('wealthComplete').textContent=euro(mw+data.portfolio.market);$('portfolioInvested').textContent=euro(data.portfolio.invested);$('portfolioMarket').textContent=euro(data.portfolio.market);const goalNow=saved(),gp=data.savingGoal?Math.min(100,goalNow/data.savingGoal*100):0;$('savingGoalNow').textContent=euro(goalNow);$('savingGoalPct').textContent=Math.round(gp)+'%';$('savingGoalTarget').textContent=euro(data.savingGoal);$('savingGoalBar').style.width=gp+'%';
$('loanBalance').textContent=euro(data.loan.balance);$('loanPayment').textContent=euro(data.loan.payment);$('loanDay').textContent='Dia '+data.loan.day;$('carFundValue').textContent=euro(data.balances.carFund);const lp=data.loan.initial?Math.max(0,Math.min(100,(1-data.loan.balance/data.loan.initial)*100)):0;$('loanProgress').style.width=lp+'%';const cp=data.carGoal?Math.min(100,data.balances.carFund/data.carGoal*100):0;$('carFundNow').textContent=euro(data.balances.carFund);$('carFundPct').textContent=Math.round(cp)+'%';$('carFundGoal').textContent=euro(data.carGoal);$('carFundBar').style.width=cp+'%';
$('budgetIncome').textContent=euro(st.income);$('budgetSpent').textContent=euro(st.expense);$('budgetReserved').textContent=euro(st.res);$('budgetAvailable').textContent=euro(st.available);const d=new Date(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate()-d.getDate()+1;$('budgetDays').textContent=days;$('budgetPerDay').textContent=euro(days?st.available/days:0);
renderRecent();renderPending();renderPaid();renderCategories();renderAccounts();renderReserves();renderCar();renderInsights();renderClosures();}
function rowHTML(title,sub,val,cls='',actions=''){return `<div class="row"><div class="row-main"><strong>${title}</strong><small>${sub}</small></div><div class="row-value"><strong class="${cls}">${val}</strong>${actions}</div></div>`}
function renderRecent(){const a=[...data.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,6);$('recentTransactions').innerHTML=a.length?a.map(t=>rowHTML(t.description,`${t.date} · ${t.type==='income'?'Receita':t.type==='expense'?'Despesa':'Transferência'}`,`${t.type==='income'?'+':t.type==='expense'?'-':''}${euro(t.amount)}`,t.type==='income'?'positive':t.type==='expense'?'negative':'neutral')).join(''):'<div class="empty">Nenhum movimento registado.</div>'}
function renderPending(){const a=data.pending.filter(p=>p.status==='pending');$('pendingList').innerHTML=a.length?a.map(p=>rowHTML(p.name,`Dia ${p.day} · ${p.category} · Por pagar`,euro(p.amount),'',`<div class="row-actions"><button class="mini primary" onclick="openPay('${p.id}')">Pagar</button><button class="mini" onclick="editPending('${p.id}')">Editar</button><button class="mini danger" onclick="deletePending('${p.id}')">Apagar</button></div>`)).join(''):'<div class="empty">Não tens despesas por pagar.</div>'}
function renderPaid(){const a=data.transactions.filter(t=>t.type==='expense'&&txMonth(t)===thisMonth()).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('paidExpenseList').innerHTML=a.length?a.map(t=>rowHTML(t.description,`${t.date} · ${t.category||'Outros'}`,`-${euro(t.amount)}`,'negative')).join(''):'<div class="empty">Ainda não existem despesas pagas este mês.</div>'}
function renderCategories(){const a=data.transactions.filter(t=>t.type==='expense'&&txMonth(t)===thisMonth()),map={};a.forEach(t=>map[t.category||'Outros']=(map[t.category||'Outros']||0)+t.amount);const max=Math.max(1,...Object.values(map));$('categoryList').innerHTML=Object.keys(map).length?Object.entries(map).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="category-item"><strong>${k}</strong><span>${euro(v)}</span><div class="bar"><span style="width:${v/max*100}%"></span></div></div>`).join(''):'<div class="empty">Sem despesas para analisar.</div>'}
function renderAccounts(){$('accountList').innerHTML=Object.entries(ACCOUNTS).map(([k,n])=>rowHTML(n,k==='insurance'?'Fora do património principal':'Incluído no património',euro(data.balances[k]),k==='insurance'?'neutral':'')).join('')}
function renderReserves(){const a=data.reserves.filter(r=>r.status==='pending');$('reserveList').innerHTML=a.length?a.map(r=>rowHTML(r.type==='savings'?'Poupança pendente':r.type==='carFund'?'Amortização pendente':'Seguro pendente',`${r.month} · Reserva pendente`,euro(r.amount),'',`<div class="row-actions"><button class="mini primary" onclick="transferReserve('${r.id}')">Transferir agora</button><button class="mini danger" onclick="cancelReserve('${r.id}')">Cancelar</button></div>`)).join(''):'<div class="empty">Sem reservas pendentes.</div>'}
function renderCar(){const a=[...data.loan.history].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('carHistory').innerHTML=a.length?a.map(h=>rowHTML(h.type==='payment'?'Prestação':'Amortização extra',h.date,`-${euro(h.amount)}`,'negative')).join(''):'<div class="empty">Nenhum movimento do carro registado.</div>'}
function renderInsights(){const st=monthStats(),year=nowISO().slice(0,4),ytx=data.transactions.filter(t=>String(t.date).startsWith(year)),months=new Set(ytx.filter(t=>t.type==='expense').map(t=>monthKey(t.date))).size||1,avg=ytx.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0)/months,pct=st.income?Math.max(0,(st.income-st.expense-st.res)/st.income*100):0,pend=data.pending.filter(p=>p.status==='pending').reduce((s,p)=>s+p.amount,0);const cards=[['Média de despesas',euro(avg)],['Poupado do rendimento',Math.round(pct)+'%'],['Reservas pendentes',euro(reserved())],['Despesas por pagar',euro(pend)],['Progresso poupança',data.savingGoal?Math.round(saved()/data.savingGoal*100)+'%':'0%'],['Dívida automóvel',euro(data.loan.balance)]];$('insightGrid').innerHTML=cards.map(([a,b])=>`<article class="insight"><small>${a}</small><strong>${b}</strong></article>`).join('')}
function renderClosures(){const a=[...data.closures].sort((a,b)=>b.year-a.year);$('yearClosures').innerHTML=a.length?a.map(c=>rowHTML(String(c.year),`Fechado em ${c.date}`,euro(c.mainWealth))).join(''):'<div class="empty">Ainda não existem anos fechados.</div>'}
function openPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));document.querySelectorAll('.bottom-nav [data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p));window.scrollTo({top:0,behavior:'smooth'});render()}
function showDialog(id){const d=$(id);if(d&&!d.open)d.showModal()}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){openPage(p.dataset.page);return}const o=e.target.closest('[data-open]');if(o){showDialog(o.dataset.open);return}const c=e.target.closest('[data-close]');if(c)$(c.dataset.close).close()});
$('themeToggle').onclick=()=>{data.theme=data.theme==='dark'?'light':'dark';save()};
['txFrom','txTo','payPendingFrom','loanPaidFrom','extraFrom'].forEach(id=>accountOptions($(id),id!=='loanPaidFrom'&&id!=='extraFrom'));
function fillBalanceForm(){$('balCurrent').value=data.balances.current;$('balSavings').value=data.balances.savings;$('balYield').value=data.balances.yield;$('balCarFund').value=data.balances.carFund;$('balExterior').value=data.balances.exterior;$('balInsurance').value=data.balances.insurance}
$('balancesDialog').addEventListener('toggle',fillBalanceForm);$('balancesForm').onsubmit=e=>{e.preventDefault();data.balances={current:+$('balCurrent').value||0,savings:+$('balSavings').value||0,yield:+$('balYield').value||0,carFund:+$('balCarFund').value||0,exterior:+$('balExterior').value||0,insurance:+$('balInsurance').value||0};save();$('balancesDialog').close()};
$('txType').onchange=()=>{const t=$('txType').value;$('txFrom').disabled=t==='income';$('txTo').disabled=t==='expense'};$('txType').dispatchEvent(new Event('change'));$('txForm').onsubmit=e=>{e.preventDefault();const t=$('txType').value,a=+$('txAmount').value;if(t==='income')credit($('txTo').value||'current',a);else if(t==='expense')debit($('txFrom').value||'current',a);else{debit($('txFrom').value,a);credit($('txTo').value,a)}data.transactions.push({id:crypto.randomUUID(),type:t,description:$('txDesc').value.trim(),amount:a,date:$('txDate').value,from:$('txFrom').value,to:$('txTo').value,category:$('txCategory').value,budget:$('txBudget').checked});save();e.target.reset();$('txDate').value=nowISO();$('txDialog').close()};
$('pendingForm').onsubmit=e=>{e.preventDefault();const id=$('pendingEditId').value,obj={id:id||crypto.randomUUID(),name:$('pendingName').value.trim(),amount:+$('pendingAmount').value,day:+$('pendingDay').value,category:$('pendingCategory').value,status:'pending'};if(id)data.pending[data.pending.findIndex(x=>x.id===id)]=obj;else data.pending.push(obj);save();e.target.reset();$('pendingEditId').value='';$('pendingDialog').close()};window.editPending=id=>{const p=data.pending.find(x=>x.id===id);$('pendingEditId').value=id;$('pendingName').value=p.name;$('pendingAmount').value=p.amount;$('pendingDay').value=p.day;$('pendingCategory').value=p.category;showDialog('pendingDialog')};window.deletePending=id=>{if(confirm('Apagar esta despesa por pagar?')){data.pending=data.pending.filter(x=>x.id!==id);save()}};window.openPay=id=>{const p=data.pending.find(x=>x.id===id);$('payPendingId').value=id;$('payPendingAmount').value=p.amount;$('payPendingDate').value=nowISO();$('payPendingFrom').value='current';showDialog('payPendingDialog')};$('payPendingForm').onsubmit=e=>{e.preventDefault();const p=data.pending.find(x=>x.id===$('payPendingId').value),a=+$('payPendingAmount').value,d=$('payPendingDate').value,from=$('payPendingFrom').value;debit(from,a);data.transactions.push({id:crypto.randomUUID(),type:'expense',description:p.name,amount:a,date:d,from,category:p.category,budget:true,pendingId:p.id});p.status='paid';p.paidDate=d;save();$('payPendingDialog').close()};
$('reserveForm').onsubmit=e=>{e.preventDefault();data.reserves.push({id:crypto.randomUUID(),type:$('reserveType').value,amount:+$('reserveAmount').value,month:thisMonth(),status:'pending'});save();e.target.reset();$('reserveDialog').close()};window.cancelReserve=id=>{const r=data.reserves.find(x=>x.id===id);if(r){r.status='cancelled';save()}};window.transferReserve=id=>{const r=data.reserves.find(x=>x.id===id);if(!r)return;const dest=r.type;const src='current';if(data.balances[src]<r.amount&&!confirm('A conta corrente pode ficar negativa. Continuar?'))return;debit(src,r.amount);credit(dest,r.amount);data.transactions.push({id:crypto.randomUUID(),type:'transfer',description:'Reserva transferida',amount:r.amount,date:nowISO(),from:src,to:dest,budget:false});r.status='transferred';r.transferDate=nowISO();save()};
$('goalDialog').addEventListener('toggle',()=>{$('savingGoalInput').value=data.savingGoal});$('goalForm').onsubmit=e=>{e.preventDefault();data.savingGoal=+$('savingGoalInput').value||0;save();$('goalDialog').close()};$('portfolioDialog').addEventListener('toggle',()=>{$('portfolioInvestedInput').value=data.portfolio.invested;$('portfolioMarketInput').value=data.portfolio.market});$('portfolioForm').onsubmit=e=>{e.preventDefault();data.portfolio.invested=+$('portfolioInvestedInput').value||0;data.portfolio.market=+$('portfolioMarketInput').value||0;save();$('portfolioDialog').close()};
$('carDialog').addEventListener('toggle',()=>{$('carBalanceInput').value=data.loan.balance;$('carInitialInput').value=data.loan.initial;$('carPaymentInput').value=data.loan.payment;$('carDayInput').value=data.loan.day;$('carGoalInput').value=data.carGoal});$('carForm').onsubmit=e=>{e.preventDefault();data.loan.balance=+$('carBalanceInput').value||0;data.loan.initial=+$('carInitialInput').value||0;data.loan.payment=+$('carPaymentInput').value||0;data.loan.day=+$('carDayInput').value||3;data.carGoal=+$('carGoalInput').value||0;save();$('carDialog').close()};
$('loanPaymentDialog').addEventListener('toggle',()=>{$('loanPaidAmount').value=data.loan.payment;$('loanCapitalAmount').value='';$('loanPaidDate').value=nowISO();$('loanPaidFrom').value='current'});$('loanPaymentForm').onsubmit=e=>{e.preventDefault();const amount=+$('loanPaidAmount').value,capital=+$('loanCapitalAmount').value,date=$('loanPaidDate').value,from=$('loanPaidFrom').value;debit(from,amount);data.loan.balance=Math.max(0,data.loan.balance-capital);data.loan.history.push({id:crypto.randomUUID(),type:'payment',amount,date,capital});data.transactions.push({id:crypto.randomUUID(),type:'expense',description:'Prestação do carro',amount,date,from,category:'Carro',budget:true});save();$('loanPaymentDialog').close()};$('extraPaymentDialog').addEventListener('toggle',()=>{$('extraDate').value=nowISO();$('extraFrom').value='carFund'});$('extraPaymentForm').onsubmit=e=>{e.preventDefault();const amount=+$('extraAmount').value,date=$('extraDate').value,from=$('extraFrom').value;debit(from,amount);data.loan.balance=Math.max(0,data.loan.balance-amount);data.loan.history.push({id:crypto.randomUUID(),type:'extra',amount,date});data.transactions.push({id:crypto.randomUUID(),type:'expense',description:'Amortização extra',amount,date,from,category:'Amortização',budget:false});save();$('extraPaymentDialog').close()};
$('closeYearBtn').onclick=()=>{const year=new Date().getFullYear();const existing=data.closures.find(c=>c.year===year);const snap={year,date:nowISO(),mainWealth:mainWealth(),completeWealth:mainWealth()+data.portfolio.market,portfolio:data.portfolio.market,loan:data.loan.balance};if(existing)Object.assign(existing,snap);else data.closures.push(snap);save()};$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({app:'DEALER$',version:26,data},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='DEALERS-backup-'+nowISO()+'.json';a.click();URL.revokeObjectURL(u)};$('importInput').onchange=async e=>{try{const j=JSON.parse(await e.target.files[0].text());if(!j.data)throw 0;if(confirm('Substituir os dados atuais pela cópia?')){data=merge(defaults,j.data);save()}}catch{alert('Cópia inválida.')}e.target.value=''};
['txDate','payPendingDate','loanPaidDate','extraDate'].forEach(id=>$(id).value=nowISO());if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render();
