'use strict';
const STORE='dealers_v25_data', THEME='dealers_v25_theme';
const $=id=>document.getElementById(id), qsa=s=>[...document.querySelectorAll(s)];
const round=v=>Math.round((Number(v||0)+Number.EPSILON)*100)/100;
const euro=v=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(v)||0);
const id=()=>crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10), monthNow=()=>today().slice(0,7);
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
const ACCOUNTS={current:'Conta corrente',savings:'Poupança',yield:'Dinheiro a render',carFund:'Fundo carro',exterior:'Exterior',insurance:'Reserva do seguro'};
const usable=['current','savings','yield','carFund','exterior'];
function blank(){return{version:25,balances:{current:0,savings:0,yield:0,carFund:0,exterior:0,insurance:0},portfolio:0,annualRate:3,savingsGoal:7000,transactions:[],pending:[],reserves:[],closedMonths:[],annualClosures:[],insurance:{monthly:0,lastPaid:0,lastDate:null,lastReturned:0},loan:{balance:17349.41,payment:318.59,annualRate:10,nextDate:'2026-08-03',history:[]}}}
function load(){try{return normalize(JSON.parse(localStorage.getItem(STORE))||blank())}catch{return blank()}}
function normalize(x){const b=blank(),s=x&&typeof x==='object'?x:{};return{...b,...s,balances:{...b.balances,...(s.balances||{})},insurance:{...b.insurance,...(s.insurance||{})},loan:{...b.loan,...(s.loan||{}),history:Array.isArray(s.loan?.history)?s.loan.history:[]},transactions:Array.isArray(s.transactions)?s.transactions:[],pending:Array.isArray(s.pending)?s.pending:[],reserves:Array.isArray(s.reserves)?s.reserves:[],closedMonths:Array.isArray(s.closedMonths)?s.closedMonths:[],annualClosures:Array.isArray(s.annualClosures)?s.annualClosures:[]}}
let vault=load(), currentPage='home';
function save(){localStorage.setItem(STORE,JSON.stringify(vault))}
function accountOptions(select,includeInsurance=false){if(!select)return;const keys=includeInsurance?[...usable,'insurance']:usable;select.innerHTML=keys.map(k=>`<option value="${k}">${ACCOUNTS[k]}</option>`).join('')}
function mainWealth(){return round(usable.reduce((s,k)=>s+Number(vault.balances[k]||0),0))}
function fullWealth(){return round(mainWealth()+Number(vault.portfolio||0))}
function monthTx(month){return vault.transactions.filter(t=>(t.budgetMonth||t.date?.slice(0,7))===month)}
function monthStats(month){const tx=monthTx(month), incomes=tx.filter(t=>t.type==='income'&&t.countBudget!==false), expenses=tx.filter(t=>t.type==='expense'&&t.countBudget!==false);const income=round(incomes.reduce((s,t)=>s+Number(t.amount),0)),expense=round(expenses.reduce((s,t)=>s+Number(t.amount),0));const reserved=round(vault.reserves.filter(r=>r.month===month&&r.status==='pending').reduce((s,r)=>s+Number(r.amount),0));const committed=round(vault.reserves.filter(r=>r.month===month&&(r.status==='pending'||r.status==='transferred')).reduce((s,r)=>s+Number(r.amount),0));const returned=round(vault.reserves.filter(r=>r.month===month&&r.status==='cancelled').reduce((s,r)=>s+Number(r.returned||0),0));return{income,expense,reserved,committed,returned,available:round(income-expense-committed),tx}}
function pendingFor(month){return vault.pending.filter(p=>p.month===month&&p.status!=='paid')}
function formatMonth(m){if(!m)return'—';const[y,mo]=m.split('-').map(Number);return new Date(y,mo-1,1).toLocaleDateString('pt-PT',{month:'long',year:'numeric'})}
function addMonth(m,n=1){const[y,mo]=m.split('-').map(Number),d=new Date(y,mo-1+n,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function changeBalance(k,delta){vault.balances[k]=round(Number(vault.balances[k]||0)+Number(delta||0))}
function txApply(t,dir=1){const a=Number(t.amount||0)*dir;if(t.type==='income')changeBalance(t.to||'current',a);if(t.type==='expense')changeBalance(t.from||'current',-a);if(t.type==='transfer'){changeBalance(t.from,-a);changeBalance(t.to,a)}}
function addTx(t){const tx={id:id(),date:today(),countBudget:true,...t};txApply(tx,1);vault.transactions.push(tx);save();render();return tx}
function deleteTx(tid){const t=vault.transactions.find(x=>x.id===tid);if(!t||t.locked)return;if(!confirm(`Eliminar “${t.description}”?`))return;txApply(t,-1);vault.transactions=vault.transactions.filter(x=>x.id!==tid);save();render()}
function listRow(main,sub,right,actions=''){return `<div class="list-row"><div class="main"><strong>${main}</strong><small>${sub}</small></div><div><strong>${right}</strong>${actions?`<div class="row-actions">${actions}</div>`:''}</div></div>`}
function empty(text){return `<div class="empty">${text}</div>`}
function renderHome(){const m=monthNow(),st=monthStats(m),pend=pendingFor(m),saved=round(vault.balances.savings+vault.balances.yield);$('homeMainWealth').textContent=euro(mainWealth());$('stateAvailable').textContent=euro(st.available);$('stateReserved').textContent=euro(st.reserved);$('stateSaved').textContent=euro(saved);$('budgetMonthLabel').textContent=formatMonth(m);$('homeBudgetIncome').textContent=euro(st.income);$('homeBudgetSpent').textContent=euro(st.expense);$('homeBudgetReserved').textContent=euro(st.reserved);$('homeBudgetAvailable').textContent=euro(st.available);$('pendingTotal').textContent=euro(pend.reduce((s,p)=>s+Number(p.amount),0));$('pendingCount').textContent=pend.length;$('homeCurrent').textContent=euro(vault.balances.current);$('homeExterior').textContent=euro(vault.balances.exterior);$('homeSavings').textContent=euro(vault.balances.savings);$('homeYield').textContent=euro(vault.balances.yield);$('homeCarFund').textContent=euro(vault.balances.carFund);$('yieldRateLabel').textContent=`${vault.annualRate}% / ano`;
 const pm=addMonth(m,-1),now=mainWealth(),prev=round(now-(monthStats(m).income-monthStats(m).expense));if(prev>0){const diff=round(now-prev),pct=diff/prev*100;$('wealthChange').textContent=`${diff>0?'↑':'↓'} ${diff>=0?'+':''}${pct.toFixed(1)}% · ${diff>=0?'+':''}${euro(diff)} vs anterior`}else $('wealthChange').textContent='Sem alterações este mês';
 $('homePendingList').innerHTML=pend.length?pend.slice(0,3).map(p=>listRow(esc(p.name),`Dia ${p.day||'—'} · Por pagar`,euro(p.amount))).join(''):empty('Sem despesas por pagar este mês.');
 const tx=[...vault.transactions].sort((a,b)=>`${b.date}${b.id}`.localeCompare(`${a.date}${a.id}`)).slice(0,7);$('recentTx').innerHTML=tx.length?tx.map(t=>{const sign=t.type==='income'?'+':t.type==='expense'?'−':'→';return listRow(esc(t.description),`${t.type==='transfer'?'Transferência':t.category||'Movimento'} · ${t.date}`,`${sign}${euro(t.amount)}`,t.locked?'':`<button class="mini-btn danger" data-del-tx="${t.id}">Eliminar</button>`)}).join(''):empty('Ainda não existem movimentos.');}
function renderBudget(){const m=$('budgetMonth').value||monthNow();$('budgetMonth').value=m;const st=monthStats(m),days=new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate(),day=m===monthNow()?new Date().getDate():days,left=Math.max(1,days-day+1);$('budgetMetrics').innerHTML=[['Total recebido',st.income],['Já gasto',st.expense],['Reservado pendente',st.reserved],['Devolvido',st.returned],['Disponível atual',st.available],['Disponível/dia',st.available/left]].map(([a,b])=>`<article><small>${a}</small><strong>${euro(b)}</strong></article>`).join('');const rs=vault.reserves.filter(r=>r.month===m);$('reserveList').innerHTML=rs.length?rs.map(r=>{const typ={savings:'Poupança',carFund:'Amortização',insurance:'Seguro'}[r.type];let acts='';if(r.status==='pending')acts=`<button class="mini-btn" data-res-edit="${r.id}">Editar</button><button class="mini-btn pay" data-res-transfer="${r.id}">Transferir agora</button><button class="mini-btn danger" data-res-cancel="${r.id}">Cancelar</button>`;return listRow(typ,`${r.status==='pending'?'Pendente':r.status==='transferred'?'Transferida':'Cancelada'} · ${formatMonth(r.month)}`,euro(r.amount),acts)}).join(''):empty('Ainda não criaste reservas para este mês.');}
function renderExpenses(){const m=$('expenseMonth').value||monthNow();$('expenseMonth').value=m;const st=monthStats(m),p=pendingFor(m),ratio=st.income?st.expense/st.income*100:0;$('expenseMetrics').innerHTML=[['Receitas',st.income],['Despesas',st.expense],['Saldo',st.income-st.expense],['Gastos / ganhos',`${ratio.toFixed(0)}%`]].map(([a,b])=>`<article><small>${a}</small><strong>${typeof b==='number'?euro(b):b}</strong></article>`).join('');$('pendingList').innerHTML=p.length?p.map(x=>listRow(esc(x.name),`Dia ${x.day||'—'} · ${x.category} · Por pagar`,euro(x.amount),`<button class="mini-btn pay" data-pay-pending="${x.id}">Pagar</button><button class="mini-btn" data-edit-pending="${x.id}">Editar</button><button class="mini-btn danger" data-del-pending="${x.id}">Apagar</button>`)).join(''):empty('Não há despesas por pagar neste mês.');const ex=vault.transactions.filter(t=>t.type==='expense'&&(t.budgetMonth||t.date?.slice(0,7))===m).sort((a,b)=>b.date.localeCompare(a.date));$('expenseHistory').innerHTML=ex.length?ex.map(t=>listRow(esc(t.description),`${t.category||'Despesa'} · ${t.date} · ${ACCOUNTS[t.from]||''}`,euro(t.amount),t.locked?'':`<button class="mini-btn danger" data-del-tx="${t.id}">Eliminar</button>`)).join(''):empty('Sem despesas pagas neste período.');}
function renderWealth(){const saved=round(vault.balances.savings+vault.balances.yield),pct=vault.savingsGoal?saved/vault.savingsGoal*100:0;$('fullWealth').textContent=euro(fullWealth());$('insuranceBalance').textContent=euro(vault.balances.insurance);$('goalSaved').textContent=euro(saved);$('goalPct').textContent=`${Math.min(100,pct).toFixed(0)}%`;$('goalTarget').textContent=euro(vault.savingsGoal);$('goalProgress').style.width=`${Math.min(100,pct)}%`;const vals=[...usable.map(k=>[ACCOUNTS[k],vault.balances[k]]),['ETF / ações',vault.portfolio]];$('wealthAccounts').innerHTML=vals.map(([a,b])=>`<article class="account-card"><span>${a}</span><strong>${euro(b)}</strong><small>${a==='ETF / ações'?'Valor variável':'Saldo atual'}</small></article>`).join('');}
function projectLoan(){let bal=Number(vault.loan.balance),count=0,totalInterest=0;const monthly=Number(vault.loan.annualRate)/100/12;while(bal>.01&&count<600){const interest=bal*monthly,capital=Math.max(0,Number(vault.loan.payment)-interest);if(capital<=0)break;bal=Math.max(0,bal-capital);totalInterest+=interest;count++}let d=new Date(`${vault.loan.nextDate||today()}T12:00:00`);d.setMonth(d.getMonth()+Math.max(0,count-1));return{count,interest:round(totalInterest),date:d.toLocaleDateString('pt-PT',{month:'long',year:'numeric'})}}
function renderCar(){const p=projectLoan(),paid=vault.loan.history.reduce((s,h)=>s+Number(h.amount||0),0);$('loanBalance').textContent=euro(vault.loan.balance);$('loanProjection').textContent=vault.loan.balance>0?`Estimativa: ${p.date}`:'Crédito liquidado';$('loanMetrics').innerHTML=[['Prestação',vault.loan.payment],['Fundo carro',vault.balances.carFund],['Prestações estimadas',`${p.count}`],['Juros estimados',p.interest]].map(([a,b])=>`<article><small>${a}</small><strong>${typeof b==='number'?euro(b):b}</strong></article>`).join('');const h=[...vault.loan.history].sort((a,b)=>b.date.localeCompare(a.date));$('loanHistory').innerHTML=h.length?h.map(x=>listRow(x.type==='payment'?'Prestação mensal':'Amortização extra',x.date,euro(x.amount))).join(''):empty('Ainda não existem pagamentos registados.');}
function renderAnnual(){$('annualList').innerHTML=vault.annualClosures.length?[...vault.annualClosures].sort((a,b)=>b.year-a.year).map(a=>listRow(`Fecho ${a.year}`,a.date,`Património ${euro(a.mainWealth)}`,`<button class="mini-btn" data-recalc-year="${a.year}">Recalcular</button>`)).join(''):empty('Ainda não existem anos fechados.');}
function renderInsights(){const m=monthNow(),st=monthStats(m),year=String(new Date().getFullYear()),months={};vault.transactions.filter(t=>t.type==='expense'&&t.date?.startsWith(year)).forEach(t=>{const k=(t.budgetMonth||t.date.slice(0,7));months[k]=(months[k]||0)+Number(t.amount)});const avg=Object.keys(months).length?Object.values(months).reduce((a,b)=>a+b,0)/Object.keys(months).length:0;const cats={};st.tx.filter(t=>t.type==='expense').forEach(t=>cats[t.category||'Outros']=(cats[t.category||'Outros']||0)+Number(t.amount));const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];const cards=[['Média de despesas',`${euro(avg)} por mês`],['Maior categoria',top?`${top[0]} · ${euro(top[1])}`:'Sem dados este mês'],['Poupança anual',`${euro(vault.balances.savings+vault.balances.yield)} de ${euro(vault.savingsGoal)}`],['Reservas pendentes',euro(st.reserved)],['Despesas por pagar',`${pendingFor(m).length} · ${euro(pendingFor(m).reduce((s,p)=>s+Number(p.amount),0))}`],['Crédito',`${euro(vault.loan.balance)} em dívida`],['Rendimento estimado',`${euro(vault.balances.yield*(vault.annualRate/100)/365)} / dia`],['Património completo',euro(fullWealth())]];$('insightGrid').innerHTML=cards.map(([a,b])=>`<article class="insight-card"><h3>${a}</h3><p>${b}</p></article>`).join('');}
function render(){renderHome();renderBudget();renderExpenses();renderWealth();renderCar();renderAnnual();renderInsights();bindDynamic()}
function showPage(p){currentPage=p;qsa('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${p}`));qsa('.bottom-nav [data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p));window.scrollTo({top:0,behavior:'smooth'});render()}
function bindDynamic(){qsa('[data-del-tx]').forEach(b=>b.onclick=()=>deleteTx(b.dataset.delTx));qsa('[data-pay-pending]').forEach(b=>b.onclick=()=>openPayPending(b.dataset.payPending));qsa('[data-edit-pending]').forEach(b=>b.onclick=()=>editPending(b.dataset.editPending));qsa('[data-del-pending]').forEach(b=>b.onclick=()=>{const p=vault.pending.find(x=>x.id===b.dataset.delPending);if(p&&confirm(`Apagar “${p.name}”?`)){vault.pending=vault.pending.filter(x=>x.id!==p.id);save();render()}});qsa('[data-res-transfer]').forEach(b=>b.onclick=()=>transferReserve(b.dataset.resTransfer));qsa('[data-res-cancel]').forEach(b=>b.onclick=()=>cancelReserve(b.dataset.resCancel));qsa('[data-res-edit]').forEach(b=>b.onclick=()=>editReserve(b.dataset.resEdit));qsa('[data-recalc-year]').forEach(b=>b.onclick=()=>closeYear(Number(b.dataset.recalcYear),true));}
function openDialog(id){const d=$(id);if(!d)return;if(id==='balancesDialog'){const box=$('balanceFields');box.innerHTML=usable.concat('insurance').map(k=>`<label>${ACCOUNTS[k]}<input data-bal="${k}" type="number" step="0.01" value="${vault.balances[k]}"></label>`).join('');$('balPortfolio').value=vault.portfolio;$('annualRate').value=vault.annualRate}if(id==='goalDialog')$('goalInput').value=vault.savingsGoal;if(id==='insuranceDialog'){$('insuranceMonthly').value=vault.insurance.monthly;$('insuranceAmount').value=''}if(id==='loanDialog'){$('loanBalanceInput').value=vault.loan.balance;$('loanPaymentInput').value=vault.loan.payment;$('loanRateInput').value=vault.loan.annualRate;$('loanNextDate').value=vault.loan.nextDate}d.showModal()}
function closeDialog(d){d.closest('dialog')?.close()}
function updateTxFields(){const type=$('txType').value;$('txFromWrap').style.display=type==='income'?'none':'block';$('txToWrap').style.display=type==='expense'?'none':'block';$('incomeTypeWrap').style.display=type==='income'?'block':'none';$('budgetToggleWrap').style.display=type==='transfer'?'none':'flex';$('budgetMonthWrap').style.display=type==='transfer'?'none':'block';if(type==='income')$('txTo').value='current';if(type==='expense')$('txFrom').value='current'}
function suggestBudgetMonth(){const date=$('txDate').value||today(),type=$('incomeType').value,day=Number(date.slice(-2)),m=date.slice(0,7);$('txBudgetMonth').value=(type==='Ordenado'&&day>=20)?addMonth(m,1):m}
function openPayPending(pid){const p=vault.pending.find(x=>x.id===pid);if(!p)return;$('payPendingId').value=pid;$('payAmount').value=p.amount;$('payDate').value=today();openDialog('payPendingDialog')}
function editPending(pid){const p=vault.pending.find(x=>x.id===pid);if(!p)return;$('pendingEditId').value=pid;$('pendingName').value=p.name;$('pendingAmount').value=p.amount;$('pendingCategory').value=p.category;$('pendingDay').value=p.day||'';$('pendingMonth').value=p.month;$('pendingRecurring').value=p.recurring||'once';openDialog('pendingDialog')}
function transferReserve(rid){const r=vault.reserves.find(x=>x.id===rid);if(!r||r.status!=='pending')return;const dest=r.type==='savings'?'savings':r.type==='carFund'?'carFund':'insurance';changeBalance('current',-r.amount);changeBalance(dest,r.amount);r.status='transferred';r.transferredDate=today();vault.transactions.push({id:id(),type:'transfer',description:`Reserva transferida — ${ACCOUNTS[dest]}`,amount:r.amount,from:null,to:dest,date:today(),countBudget:false,locked:true,reserveId:r.id});save();render()}
function cancelReserve(rid){const r=vault.reserves.find(x=>x.id===rid);if(!r||r.status!=='pending')return;if(!confirm('Cancelar esta reserva? O valor regressa ao disponível do mês.'))return;r.status='cancelled';r.returned=r.amount;r.cancelledDate=today();save();render()}
function editReserve(rid){const r=vault.reserves.find(x=>x.id===rid);if(!r)return;const v=prompt('Novo valor da reserva (€):',r.amount);if(v===null)return;const n=Number(v);if(n>=0){r.amount=round(n);save();render()}}
function closeYear(year=new Date().getFullYear(),replace=false){const tx=vault.transactions.filter(t=>t.date?.startsWith(String(year))),income=tx.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0),expense=tx.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0);const obj={year,date:today(),income:round(income),expense:round(expense),mainWealth:mainWealth(),fullWealth:fullWealth(),savings:round(vault.balances.savings+vault.balances.yield),carDebt:vault.loan.balance,portfolio:vault.portfolio};const idx=vault.annualClosures.findIndex(x=>x.year===year);if(idx>=0)vault.annualClosures[idx]=obj;else vault.annualClosures.push(obj);save();render()}
function init(){const theme=localStorage.getItem(THEME)||'dark';document.documentElement.dataset.theme=theme;['txFrom','txTo','payFrom','transferFrom','transferTo','insuranceFallback','paymentFrom','extraFrom'].forEach(x=>accountOptions($(x)));$('budgetMonth').value=monthNow();$('expenseMonth').value=monthNow();$('txDate').value=today();$('txBudgetMonth').value=monthNow();$('pendingMonth').value=monthNow();$('reserveMonth').value=monthNow();$('transferDate').value=today();$('paymentDate').value=today();$('extraDate').value=today();
 qsa('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));qsa('[data-open]').forEach(b=>b.addEventListener('click',()=>openDialog(b.dataset.open)));qsa('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b)));$('themeToggle').onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem(THEME,n)};$('budgetMonth').onchange=render;$('expenseMonth').onchange=render;$('txType').onchange=updateTxFields;$('txDate').onchange=suggestBudgetMonth;$('incomeType').onchange=suggestBudgetMonth;
 $('txForm').onsubmit=e=>{e.preventDefault();const type=$('txType').value,amount=Number($('txAmount').value),date=$('txDate').value,desc=$('txDesc').value.trim(),cat=$('txCategory').value;if(!amount||!desc)return;const t={type,amount,date,description:desc,category:cat,from:type==='income'?null:$('txFrom').value,to:type==='expense'?null:$('txTo').value,countBudget:type==='transfer'?false:$('txBudget').checked,budgetMonth:type==='transfer'?null:$('txBudgetMonth').value,incomeType:type==='income'?$('incomeType').value:null};if(type==='transfer'&&t.from===t.to)return alert('Escolhe uma origem e destino diferentes.');if(type!=='income'&&vault.balances[t.from]<amount&&!confirm('O saldo desta origem ficará negativo. Continuar?'))return;addTx(t);$('txForm').reset();$('txDate').value=today();$('txBudgetMonth').value=monthNow();$('txDialog').close();updateTxFields()};
 $('balancesForm').onsubmit=e=>{e.preventDefault();qsa('[data-bal]').forEach(i=>vault.balances[i.dataset.bal]=round(Number(i.value)));vault.portfolio=round(Number($('balPortfolio').value));vault.annualRate=Number($('annualRate').value)||0;save();$('balancesDialog').close();render()};
 $('pendingForm').onsubmit=e=>{e.preventDefault();const edit=$('pendingEditId').value,obj={name:$('pendingName').value.trim(),amount:round(Number($('pendingAmount').value)),category:$('pendingCategory').value,day:Number($('pendingDay').value)||null,month:$('pendingMonth').value,recurring:$('pendingRecurring').value,status:'pending'};if(edit){Object.assign(vault.pending.find(x=>x.id===edit),obj)}else{vault.pending.push({id:id(),...obj});if(obj.recurring==='monthly'){for(let i=1;i<=11;i++)vault.pending.push({id:id(),...obj,month:addMonth(obj.month,i),seriesMonth:obj.month})}}save();$('pendingDialog').close();$('pendingForm').reset();$('pendingEditId').value='';$('pendingMonth').value=monthNow();render()};
 $('payPendingForm').onsubmit=e=>{e.preventDefault();const p=vault.pending.find(x=>x.id===$('payPendingId').value);if(!p)return;const amount=round(Number($('payAmount').value)),date=$('payDate').value,from=$('payFrom').value;if(vault.balances[from]<amount&&!confirm('O saldo desta origem ficará negativo. Continuar?'))return;const tx=addTx({type:'expense',description:p.name,amount,date,category:p.category,from,countBudget:true,budgetMonth:p.month,pendingId:p.id,locked:false});p.status='paid';p.paidAmount=amount;p.paidDate=date;p.from=from;p.movementId=tx.id;save();$('payPendingDialog').close();render()};
 $('reserveForm').onsubmit=e=>{e.preventDefault();vault.reserves.push({id:id(),type:$('reserveType').value,amount:round(Number($('reserveAmount').value)),month:$('reserveMonth').value,status:'pending',created:today()});save();$('reserveDialog').close();$('reserveForm').reset();$('reserveMonth').value=monthNow();render()};
 $('transferForm').onsubmit=e=>{e.preventDefault();const from=$('transferFrom').value,to=$('transferTo').value,amount=round(Number($('transferAmount').value));if(from===to)return alert('Escolhe saldos diferentes.');if(vault.balances[from]<amount&&!confirm('O saldo da origem ficará negativo. Continuar?'))return;addTx({type:'transfer',description:`Transferência: ${ACCOUNTS[from]} → ${ACCOUNTS[to]}`,amount,date:$('transferDate').value,from,to,countBudget:false,category:'Transferência'});$('transferDialog').close();$('transferForm').reset();$('transferDate').value=today()};
 $('goalForm').onsubmit=e=>{e.preventDefault();vault.savingsGoal=round(Number($('goalInput').value));save();$('goalDialog').close();render()};
 $('insuranceForm').onsubmit=e=>{e.preventDefault();vault.insurance.monthly=round(Number($('insuranceMonthly').value));const action=$('insuranceAction').value,amount=round(Number($('insuranceAmount').value));if(action==='add'){changeBalance('current',-amount);changeBalance('insurance',amount);vault.transactions.push({id:id(),type:'transfer',description:'Reforço da reserva do seguro',amount,date:today(),from:'current',to:'insurance',countBudget:false,locked:true})}if(action==='withdraw'){const a=Math.min(amount,vault.balances.insurance);changeBalance('insurance',-a);changeBalance('current',a);vault.transactions.push({id:id(),type:'transfer',description:'Retirada da reserva do seguro',amount:a,date:today(),from:'insurance',to:'current',countBudget:false,locked:true})}if(action==='pay'){let remaining=amount,used=Math.min(vault.balances.insurance,remaining);changeBalance('insurance',-used);remaining=round(remaining-used);if(remaining>0)changeBalance($('insuranceFallback').value,-remaining);const leftover=vault.balances.insurance;if(leftover>0){changeBalance('insurance',-leftover);changeBalance('current',leftover)}vault.insurance.lastPaid=amount;vault.insurance.lastDate=today();vault.insurance.lastReturned=leftover;vault.transactions.push({id:id(),type:'expense',description:'Seguro automóvel',amount,date:today(),from:$('insuranceFallback').value,category:'Carro',countBudget:true,budgetMonth:monthNow(),locked:true})}save();$('insuranceDialog').close();render()};
 $('loanForm').onsubmit=e=>{e.preventDefault();vault.loan.balance=round(Number($('loanBalanceInput').value));vault.loan.payment=round(Number($('loanPaymentInput').value));vault.loan.annualRate=Number($('loanRateInput').value)||0;vault.loan.nextDate=$('loanNextDate').value;save();$('loanDialog').close();render()};
 $('paymentForm').onsubmit=e=>{e.preventDefault();const amount=round(Number($('paymentAmount').value||vault.loan.payment)),from=$('paymentFrom').value,date=$('paymentDate').value,interest=round(vault.loan.balance*(vault.loan.annualRate/100/12)),capital=round(Math.min(vault.loan.balance,Math.max(0,amount-interest)));changeBalance(from,-amount);vault.loan.balance=round(Math.max(0,vault.loan.balance-capital));vault.loan.history.push({id:id(),type:'payment',amount,date,interest,capital});vault.transactions.push({id:id(),type:'expense',description:'Prestação do Audi',amount,date,from,category:'Carro',countBudget:true,budgetMonth:date.slice(0,7),locked:true});vault.loan.nextDate=addMonth(date.slice(0,7),1)+'-'+date.slice(-2);save();$('paymentDialog').close();render()};
 $('extraForm').onsubmit=e=>{e.preventDefault();const amount=round(Number($('extraAmount').value)),from=$('extraFrom').value,date=$('extraDate').value;changeBalance(from,-amount);vault.loan.balance=round(Math.max(0,vault.loan.balance-amount));vault.loan.history.push({id:id(),type:'extra',amount,date});vault.transactions.push({id:id(),type:'expense',description:'Amortização extraordinária do Audi',amount,date,from,category:'Amortização',countBudget:true,budgetMonth:date.slice(0,7),locked:true});save();$('extraDialog').close();render()};
 $('closeMonthBtn').onclick=()=>{const m=$('budgetMonth').value;if(!vault.closedMonths.includes(m))vault.closedMonths.push(m);save();alert(`${formatMonth(m)} marcado como fechado.`)};$('closeYearBtn').onclick=()=>closeYear();updateTxFields();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=25.0.0').catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
