const KEY="DEALERS_V24";const $=id=>document.getElementById(id);const euro=n=>new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(Number(n)||0);const iso=()=>new Date().toISOString().slice(0,10);const month=()=>iso().slice(0,7);const round=n=>Math.round((Number(n)||0)*100)/100;
const monthLabel=k=>new Intl.DateTimeFormat("pt-PT",{month:"long",year:"numeric"}).format(new Date(k+"-01")).replace(/^./,x=>x.toUpperCase());
const nextMonth=k=>{let d=new Date(k+"-01");d.setMonth(d.getMonth()+1);return d.toISOString().slice(0,7)};
const accountNames={current:"Conta corrente",savings:"Poupança",yield:"Dinheiro a render",carFund:"Fundo carro",external:"Exterior"};
const defaultData=()=>({balances:{current:0,savings:0,yield:0,carFund:0},goal:7000,rate:0,transactions:[],bills:[],reserves:[],investments:[],loan:{initial:0,balance:0,payment:0,rate:0,next:"",payments:0,history:[]},theme:"dark"});
let db=JSON.parse(localStorage.getItem(KEY)||"null")||defaultData();
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function normalize(){db.balances={...defaultData().balances,...(db.balances||{})};db.transactions ||= [];db.bills ||= [];db.reserves ||= [];db.investments ||= [];db.loan={...defaultData().loan,...(db.loan||{})};save()}
normalize();
function moneyAccounts(){return db.balances.current+db.balances.savings+db.balances.yield+db.balances.carFund}
function reservePending(k=month()){return db.reserves.reduce((s,r)=>s+(r.month===k&&!r.transferred?r.amount:0),0)}
function billsPending(k=month()){return db.bills.filter(b=>b.month===k&&!b.paid).reduce((s,b)=>s+b.amount,0)}
function expenses(k=month()){return db.transactions.filter(t=>t.type==="expense"&&t.date.slice(0,7)===k).reduce((s,t)=>s+t.amount,0)}
function income(k=month()){return db.transactions.filter(t=>t.type==="income"&&t.budgetMonth===k&&t.countsBudget).reduce((s,t)=>s+t.amount,0)}
function savingsTotal(){return db.balances.savings+db.balances.yield}
function availableBudget(k=month()){return income(k)-expenses(k)-reservePending(k)}
function budgetMonthFor(date,kind){let k=date.slice(0,7),d=+date.slice(8,10);if(kind==="salary"&&d>=20)return nextMonth(k);if(kind==="bonus"&&d<=20)return k;return k}
function addTx(t){t.id=crypto.randomUUID();db.transactions.push(t);save()}
function render(){
  const k=month(), avail=moneyAccounts()-reservePending(k), saved=savingsTotal(), withRes=moneyAccounts()+reservePending(k);
  $("wealthAvailable").textContent=euro(avail);$("wealthWithReservations").textContent=euro(withRes);$("stateAvailable").textContent=euro(avail);$("stateReserved").textContent=euro(reservePending(k));$("stateSaved").textContent=euro(saved);
  $("homeBudgetTitle").textContent=monthLabel(k);$("homeIncome").textContent=euro(income(k));$("homeReserved").textContent=euro(reservePending(k));$("homeSpent").textContent=euro(expenses(k));$("homeBudgetAvailable").textContent=euro(availableBudget(k));$("homeCurrent").textContent=euro(db.balances.current);$("homeSavings").textContent=euro(db.balances.savings);$("homeYield").textContent=euro(db.balances.yield);$("homeExpenses").textContent=euro(expenses(k));
  const totalIncome=income(k), pct=totalIncome?Math.min(100,expenses(k)/totalIncome*100):0;$("homeBudgetProgress").style.width=pct+"%";
  const bp=db.bills.filter(b=>b.month===k&&!b.paid);$("homeBills").textContent=`${euro(bp.reduce((s,b)=>s+b.amount,0))} · ${bp.length} ${bp.length===1?"despesa":"despesas"}`;
  const goal=Math.max(0,db.goal),gp=goal?Math.min(100,saved/goal*100):0;$("goalNow").textContent=euro(saved);$("goalTarget").textContent=euro(goal);$("goalPct").textContent=Math.round(gp)+"%";$("goalProgress").style.width=gp+"%";
  renderRecent();renderBudget();renderExpenses();renderWealth();renderCar();renderInsights();renderDialogs();
}
function renderRecent(){const items=[...db.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);$("recentList").innerHTML=items.length?items.map(t=>txHtml(t)).join(""):'<p class="muted">Ainda não existem movimentos.</p>'}
function txHtml(t){let sign=t.type==="income"?"+":"−";let cls=t.type==="income"?"positive":"negative";return `<div class="tx"><span class="tx-icon">${t.type==="income"?"↑":t.type==="transfer"?"⇄":"↓"}</span><div><strong>${t.desc}</strong><small>${t.date} · ${t.category||"Transferência"}</small></div><strong class="${cls}">${sign}${euro(t.amount)}</strong></div>`}
function renderBudget(){let k=$("budgetMonth").value||month();$("budgetAvailable").textContent=euro(availableBudget(k));const its=db.transactions.filter(t=>t.type==="income"&&t.budgetMonth===k&&t.countsBudget);$("budgetSalary").textContent=euro(its.filter(t=>t.kind==="salary").reduce((s,t)=>s+t.amount,0));$("budgetBonus").textContent=euro(its.filter(t=>t.kind==="bonus").reduce((s,t)=>s+t.amount,0));$("budgetOther").textContent=euro(its.filter(t=>!["salary","bonus"].includes(t.kind)).reduce((s,t)=>s+t.amount,0));$("budgetIncome").textContent=euro(income(k));$("reserveList").innerHTML=db.reserves.filter(r=>r.month===k&&!r.transferred).map((r,i)=>`<div class="balance-row"><div><strong>${r.name}</strong><small>${euro(r.amount)} pendente</small></div><button class="text-btn" data-settle="${r.id}">Transferir</button></div>`).join("")||'<p class="muted">Sem reservas pendentes neste mês.</p>';const bills=db.bills.filter(b=>b.month===k);$("billList").innerHTML=bills.map(b=>`<div class="balance-row"><div><strong>${b.desc}</strong><small>${b.day?`Dia ${b.day} · `:""}${euro(b.amount)}</small></div><button class="text-btn" data-pay="${b.id}" ${b.paid?"disabled":""}>${b.paid?"Paga":"Pagar"}</button></div>`).join("")||'<p class="muted">Sem despesas por pagar.</p>'}
function renderExpenses(){const k=$("expenseMonth").value||month(),arr=db.transactions.filter(t=>t.type==="expense"&&t.date.slice(0,7)===k);let total=arr.reduce((s,t)=>s+t.amount,0);let cats={};arr.forEach(t=>cats[t.category]=(cats[t.category]||0)+t.amount);let top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];$("expenseTotal").textContent=euro(total);$("expenseDaily").textContent=euro(total/(new Date().getDate()||1));$("expenseTop").textContent=top?`${top[0]} · ${euro(top[1])}`:"—";$("expenseRatio").textContent=income(k)?Math.round(total/income(k)*100)+"%":"0%";$("expenseList").innerHTML=arr.sort((a,b)=>b.date.localeCompare(a.date)).map(txHtml).join("")||'<p class="muted">Sem despesas pagas neste mês.</p>'}
function renderWealth(){$("wealthMain").textContent=euro(moneyAccounts());$("wealthAll").textContent=euro(moneyAccounts()+reservePending());$("wealthMarket").textContent=euro(db.investments.reduce((s,i)=>s+i.current,0));$("balanceList").innerHTML=Object.entries(db.balances).map(([k,v])=>`<div class="balance-row"><div><strong>${accountNames[k]}</strong><small>Saldo atual</small></div><strong>${euro(v)}</strong></div>`).join("");$("investmentList").innerHTML=db.investments.map(i=>`<div class="investment"><div><strong>${i.name}</strong><small>${i.ticker||"Sem ticker"}</small></div><strong>${euro(i.current)}</strong></div>`).join("")||'<p class="muted">Ainda não existem ETF ou ações registados.</p>'}
function renderCar(){const l=db.loan;$("loanBalance").textContent=euro(l.balance);$("loanInitial").textContent=euro(l.initial);$("loanPayment").textContent=euro(l.payment);$("loanNext").textContent=l.next||"—";$("loanPayments").textContent=l.payments||0;let paid=Math.max(0,l.initial-l.balance);$("loanPaid").textContent=euro(paid);$("loanProgress").style.width=(l.initial?Math.min(100,paid/l.initial*100):0)+"%";let interest=l.balance*(l.rate/100)/12;$("loanInterest").textContent=euro(interest);$("loanHistory").innerHTML=l.history.map(h=>`<div class="tx"><span class="tx-icon">🚘</span><div><strong>${h.desc}</strong><small>${h.date}</small></div><strong>${euro(h.amount)}</strong></div>`).join("")||'<p class="muted">Sem pagamentos registados.</p>'}
function renderInsights(){const months=[...new Set(db.transactions.filter(t=>t.type==="expense").map(t=>t.date.slice(0,7)))];let avg=months.length?months.reduce((s,m)=>s+expenses(m),0)/months.length:0;let inc=income(month()),saveRate=inc?Math.max(0,(inc-expenses(month()))/inc*100):0;$("insAvg").textContent=euro(avg);$("insSaveRate").textContent=Math.round(saveRate)+"%";$("insReserve").textContent=euro(reservePending());$("insBills").textContent=euro(billsPending())}
function renderDialogs(){$("bCurrent").value=db.balances.current;$("bSavings").value=db.balances.savings;$("bYield").value=db.balances.yield;$("bCarFund").value=db.balances.carFund;$("goalInput").value=db.goal;$("rateInput").value=db.rate;$("cInitial").value=db.loan.initial;$("cBalance").value=db.loan.balance;$("cPayment").value=db.loan.payment;$("cRate").value=db.loan.rate;$("cNext").value=db.loan.next;$("cPayments").value=db.loan.payments;$("pDate").value=iso();$("xDate").value=iso();$("billMonth").value=month()}
function populateMonths(){const keys=new Set([month(),nextMonth(month()),...db.transactions.map(t=>t.date.slice(0,7)),...db.bills.map(b=>b.month)]);for(const id of ["budgetMonth","expenseMonth"]){const el=$(id),cur=el.value||month();el.innerHTML=[...keys].sort().reverse().map(k=>`<option value="${k}">${monthLabel(k)}</option>`).join("");el.value=keys.has(cur)?cur:month()}}
function page(name){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id==="page-"+name));document.querySelectorAll(".bottom-nav [data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===name));scrollTo(0,0)}
document.addEventListener("click",e=>{const open=e.target.closest("[data-open]"),pg=e.target.closest("[data-page]"),close=e.target.closest("[data-close]");if(open)$(open.dataset.open).showModal();if(pg&&!pg.closest("dialog"))page(pg.dataset.page);if(close)$(close.dataset.close).close();const mode=e.target.closest("[data-mode]");if(mode){document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));mode.classList.add("active");window.moveMode=mode.dataset.mode; $("mKindWrap").style.display=window.moveMode==="income"?"block":"none";$("mToWrap").style.display=window.moveMode==="transfer"?"block":"none";$("mCategoryWrap").style.display=window.moveMode==="transfer"?"none":"block";$("budgetChoice").style.display=window.moveMode==="income"?"grid":"none"}const b=e.target.closest("[data-budget]");if(b){document.querySelectorAll("[data-budget]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("budgetChoice").dataset.value=b.dataset.budget}const settle=e.target.closest("[data-settle]");if(settle){const r=db.reserves.find(x=>x.id===settle.dataset.settle);if(r&&db.balances.current>=r.amount){db.balances.current-=r.amount;db.balances.savings+=r.amount;r.transferred=true;r.transferredDate=iso();save();render()}}const pay=e.target.closest("[data-pay]");if(pay){const bll=db.bills.find(x=>x.id===pay.dataset.pay);if(bll&&!bll.paid){if(db.balances.current<bll.amount)return alert("Saldo insuficiente na conta corrente.");db.balances.current-=bll.amount;bll.paid=true;addTx({type:"expense",desc:bll.desc,amount:bll.amount,date:iso(),category:bll.category||"Contas",countsBudget:true,budgetMonth:bll.month});render()}}});
$("movementForm").addEventListener("submit",e=>{e.preventDefault();let mode=window.moveMode||"income",date=$("mDate").value,amt=round($("mAmount").value),from=$("mFrom").value,to=$("mTo").value;if(!amt)return; if(mode==="income"){db.balances.current+=amt;let counts=document.querySelector("[data-budget].active")?.dataset.budget!=="no";let kind=$("mKind").value;addTx({type:"income",desc:$("mDesc").value,amount:amt,date,category:$("mCategory").value,kind,countsBudget:counts,budgetMonth:counts?budgetMonthFor(date,kind):""})}else if(mode==="expense"){if(db.balances[from]<amt)return alert("Saldo insuficiente.");db.balances[from]-=amt;addTx({type:"expense",desc:$("mDesc").value,amount:amt,date,category:$("mCategory").value,countsBudget:true,budgetMonth:date.slice(0,7)})}else{if(db.balances[from]<amt)return alert("Saldo insuficiente.");db.balances[from]-=amt;if(to!=="external")db.balances[to]+=amt;addTx({type:"transfer",desc:$("mDesc").value,amount:amt,date,from,to})}save();$("movementDialog").close();e.target.reset();render()});
$("balancesForm").addEventListener("submit",e=>{e.preventDefault();db.balances={current:round($("bCurrent").value),savings:round($("bSavings").value),yield:round($("bYield").value),carFund:round($("bCarFund").value)};save();$("balancesDialog").close();render()});
$("settingsForm").addEventListener("submit",e=>{e.preventDefault();db.goal=round($("goalInput").value);db.rate=round($("rateInput").value);save();$("settingsDialog").close();render()});
$("reserveForm").addEventListener("submit",e=>{e.preventDefault();db.reserves.push({id:crypto.randomUUID(),name:$("rName").value,amount:round($("rAmount").value),month:month(),transferred:false});save();$("reserveDialog").close();e.target.reset();render()});
$("billForm").addEventListener("submit",e=>{e.preventDefault();db.bills.push({id:crypto.randomUUID(),month:$("billMonth").value,desc:$("billDesc").value,amount:round($("billAmount").value),day:$("billDay").value,category:$("billCategory").value,paid:false});save();$("billDialog").close();e.target.reset();render()});
$("investmentForm").addEventListener("submit",e=>{e.preventDefault();db.investments.push({id:crypto.randomUUID(),name:$("iName").value,ticker:$("iTicker").value,invested:round($("iInvested").value),current:round($("iCurrent").value)});save();$("investmentDialog").close();e.target.reset();render()});
$("carForm").addEventListener("submit",e=>{e.preventDefault();db.loan={...db.loan,initial:round($("cInitial").value),balance:round($("cBalance").value),payment:round($("cPayment").value),rate:round($("cRate").value),next:$("cNext").value,payments:+$("cPayments").value};save();$("carDialog").close();render()});
$("paymentForm").addEventListener("submit",e=>{e.preventDefault();if(db.loan.payment>db.balances.current)return alert("Saldo insuficiente.");db.balances.current-=db.loan.payment;let interest=round(db.loan.balance*(db.loan.rate/100)/12),capital=Math.max(0,round(db.loan.payment-interest));db.loan.balance=Math.max(0,round(db.loan.balance-capital));db.loan.payments++;db.loan.history.push({desc:"Prestação mensal",amount:db.loan.payment,date:$("pDate").value});addTx({type:"expense",desc:"Prestação do carro",amount:db.loan.payment,date:$("pDate").value,category:"Carro",countsBudget:true,budgetMonth:$("pDate").value.slice(0,7)});save();$("paymentDialog").close();render()});
$("extraForm").addEventListener("submit",e=>{e.preventDefault();let a=round($("xAmount").value),s=$("xSource").value;if(a>db.loan.balance)return alert("O valor ultrapassa a dívida.");if(db.balances[s]<a)return alert("Saldo insuficiente.");db.balances[s]-=a;db.loan.balance=round(db.loan.balance-a);db.loan.history.push({desc:"Amortização extraordinária",amount:a,date:$("xDate").value});addTx({type:"expense",desc:"Amortização extraordinária",amount:a,date:$("xDate").value,category:"Amortização",countsBudget:true,budgetMonth:$("xDate").value.slice(0,7)});save();$("extraDialog").close();render()});
$("themeToggle").onclick=()=>{db.theme=db.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=db.theme;save()};document.documentElement.dataset.theme=db.theme;
$("budgetMonth").onchange=render;$("expenseMonth").onchange=render;populateMonths();window.moveMode="income";$("mDate").value=iso();render();
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=24.0.0").catch(()=>{});
